name: Docker Build and Push

on:
  workflow_call:
    inputs:

      context:
        description: "Docker context path"
        default: .
        type: string

      timeout:
        description: "Timeout for jobs in minutes"
        default: 15
        type: number

      repository:
        description: "Repository"
        type: string


    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: ${{ inputs.timeout }}
    steps:
    - uses: 'actions/checkout@v3'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ inputs.repository }}

        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

        push: true
        tags: ${{ steps.meta.outputs.tags }}
